services:
  # 1. O nosso Banco de Dados
  postgres-db:
    image: postgres:15-alpine
    container_name: kanban-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: kanban_db
    ports:
      - "5432:5432" # Expondo para usarmos ferramentas gráficas como o DBeaver
    volumes:
      - postgres-data:/var/lib/postgresql/data # O HD externo!

  # 2. A nossa API Spring Boot
  kanban-api:
    build: . # A mágica: O Compose vai olhar o Dockerfile, fazer o multi-stage build sozinho!
    container_name: kanban-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/kanban_db # O uso do DNS Interno!
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres-db # Ordem de inicialização: A API só liga depois do banco

# Declarando o cofre blindado para o Docker criar
volumes:
  postgres-data: