name: CI - Validação de Código e Testes
# 1. Os Gatilhos do Git Flow
on:
  push:
    branches:
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - develop

jobs:
  validacao_e_testes:
    name: Compilação e Testes Unitários
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o Repositório
        uses: actions/checkout@v4

      - name: Configurar o Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # O passo mais importante: A garantia de qualidade!
      - name: Executar Testes Unitários
        run: mvn clean test

      # Só chega aqui se os testes passarem
      - name: Garantir que compila (Build)
        run: mvn clean package -DskipTests